import mongoose from "mongoose";
import dotenv from "dotenv";
import Card from "./models/Card.js";
import Listing from "./models/Listing.js";

dotenv.config();

const cards = [
    {
        group: "BTS",
        idol: "Jungkook",
        album: "Map of the Soul: 7",
        version: "Version 2",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 46.5,
        imageUrl: "https://i.pinimg.com/736x/c3/36/50/c3365081a1ad4280c209c7b3bbd3822e.jpg",
        aliases: [
            "JK MOTS7 Ver 2",
            "Jungkook MOTS7",
            "BTS Jungkook Map of the Soul 7",
        ],
    },
    {
        group: "BTS",
        idol: "Jungkook",
        album: "BE",
        version: "Essential Edition",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 46.5,
        imageUrl: "https://i.pinimg.com/564x/c9/ea/a7/c9eaa7711fedf0d84235abb6d83a6033.jpg",
        aliases: [
            "JK BE Essential",
            "Jungkook BE PC",
            "BTS BE Jungkook",
        ],
    },
    {
        group: "BTS",
        idol: "Jimin",
        album: "Proof",
        version: "Standard Edition",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 28,
        imageUrl: "https://i.pinimg.com/736x/af/f8/97/aff897c3955e0681833a1e58f9178b32.jpg",
        aliases: [
            "Jimin Proof PC",
            "BTS Proof Jimin",
            "Park Jimin Proof",
        ],
    },
    {
        group: "BTS",
        idol: "V",
        album: "Love Yourself: Tear",
        version: "Y Version",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 38,
        imageUrl: "https://i.pinimg.com/736x/12/6c/c6/126cc6458abb97b598f9585c82ac5d22.jpg",
        aliases: [
            "Taehyung Tear Y",
            "V Love Yourself Tear",
            "BTS Tae Tear PC",
        ],
    },
    {
        group: "BTS",
        idol: "RM",
        album: "Love Yourself: Answer",
        version: "S Version",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 23,
        imageUrl: "https://i.pinimg.com/736x/c1/73/74/c173748dd9eb80b1831d4fb2ef40b7c8.jpg",
        aliases: [
            "Namjoon Answer S",
            "RM Love Yourself Answer",
            "BTS RM Answer PC",
        ],
    },
    {
        group: "BLACKPINK",
        idol: "Jennie",
        album: "Born Pink",
        version: "Pink Ver.",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 24,
        imageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2025/05/07/681bc0bcfe4c68da89f269a8/l_681bc0ca1493776d3bcc2ac8.jpg",
        aliases: [
            "Jennie Born Pink",
            "BP Jennie Pink Ver",
            "Nini Born Pink PC",
        ],
    },
    {
        group: "BLACKPINK",
        idol: "Lisa",
        album: "The Album",
        version: "Version 4",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 22,
        imageUrl: "https://i.pinimg.com/236x/14/57/00/14570035104edb5fafa6e51f22027132.jpg",
        aliases: [
            "Lisa The Album Ver 4",
            "BP Lisa The Album",
            "Lalisa Album PC",
        ],
    },
    {
        group: "BLACKPINK",
        idol: "Jisoo",
        album: "Kill This Love",
        version: "Black Ver.",
        cardType: "POB",
        rarity: "Rare",
        condition: "Excellent",
        askingPrice: 42,
        imageUrl: "https://i.pinimg.com/736x/82/af/92/82af92a004f199ffdfe83bd2b3bd57b7.jpg",
        aliases: [
            "Jisoo KTL POB",
            "BP Jisoo Kill This Love",
            "Chu KTL PC",
        ],
    },
    {
        group: "LE SSERAFIM",
        idol: "Sakura",
        album: "Antifragile",
        version: "Midnight Onyx Ver.",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 18,
        imageUrl: "https://i.pinimg.com/236x/0b/16/79/0b1679de7eba856cd4630c87a67a12bd.jpg",
        aliases: [
            "Sakura Antifragile",
            "LSF Sakura Midnight Onyx",
            "Kkura Antifragile PC",
        ],
    },
    {
        group: "LE SSERAFIM",
        idol: "Chaewon",
        album: "Unforgiven",
        version: "Weverse POB",
        cardType: "POB",
        rarity: "Rare",
        condition: "Near Mint",
        askingPrice: 36,
        imageUrl: "https://i.etsystatic.com/48188581/r/il/28980f/7015231002/il_680x540.7015231002_6b8t.jpg",
        aliases: [
            "Chaewon Unforgiven POB",
            "LSF Chaewon Weverse",
            "Pupu Unforgiven PC",
        ],
    },
    {
        group: "LE SSERAFIM",
        idol: "Yunjin",
        album: "Easy",
        version: "Balmy Flex Ver.",
        cardType: "Album photocard",
        rarity: "Uncommon",
        condition: "Excellent",
        askingPrice: 16,
        imageUrl: "https://i.pinimg.com/236x/f1/f9/2e/f1f92e3024129372f5c18cc8d573f11b.jpg",
        aliases: [
            "Yunjin Easy Balmy Flex",
            "LSF Yunjin Easy",
            "Jen Easy PC",
        ],
    },
    {
        group: "NewJeans",
        idol: "Hanni",
        album: "Get Up",
        version: "Bunny Beach Bag Ver.",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 18.99,
        imageUrl: "https://i.ebayimg.com/images/g/ZMoAAOSwN9dkvUbR/s-l1600.webp",
        aliases: [
            "Hanni Get Up",
            "NJ Hanni Bunny Beach Bag",
            "Pham Get Up PC",
        ],
    },
    {
        group: "NewJeans",
        idol: "Minji",
        album: "OMG",
        version: "Message Card Ver.",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Mint",
        askingPrice: 17,
        imageUrl: "https://i.pinimg.com/474x/78/f9/1a/78f91ad9e097c5f25ae249d445c6ad95.jpg",
        aliases: [
            "Minji OMG",
            "NJ Minji Message Card",
            "NewJeans OMG Minji PC",
        ],
    },
    {
        group: "NewJeans",
        idol: "Haerin",
        album: "New Jeans",
        version: "Bluebook Ver.",
        cardType: "Lucky draw",
        rarity: "Rare",
        condition: "Near Mint",
        askingPrice: 48,
        imageUrl: "https://i.ebayimg.com/thumbs/images/g/ZMoAAOSwN9dkvUbR/s-l500.jpg",
        aliases: [
            "Haerin Bluebook Lucky Draw",
            "NJ Haerin New Jeans",
            "Kitty Kang LD",
        ],
    },
    {
        group: "TWICE",
        idol: "Sana",
        album: "Formula of Love",
        version: "Study About Love Ver.",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 14,
        imageUrl: "https://i.pinimg.com/474x/78/f9/1a/78f91ad9e097c5f25ae249d445c6ad95.jpg",
        aliases: [
            "Sana FOL",
            "TW Sana Formula of Love",
            "Sha Sha Study About Love",
        ],
    },
    {
        group: "TWICE",
        idol: "Mina",
        album: "Ready To Be",
        version: "Digipack Ver.",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Excellent",
        askingPrice: 12,
        imageUrl: "https://i.pinimg.com/474x/56/0b/85/560b8500cefa42ec6c64defb6f2d871c.jpg",
        aliases: [
            "Mina Ready To Be",
            "TW Mina Digipack",
            "Penguin RTB PC",
        ],
    },
    {
        group: "TWICE",
        idol: "Nayeon",
        album: "Taste of Love",
        version: "Taste Ver.",
        cardType: "POB",
        rarity: "Rare",
        condition: "Near Mint",
        askingPrice: 31,
        imageUrl: "https://i.pinimg.com/474x/56/0b/85/560b8500cefa42ec6c64defb6f2d871c.jpg",
        aliases: [
            "Nayeon TOL POB",
            "TW Nayeon Taste of Love",
            "Nabong Taste PC",
        ],
    },
    {
        group: "Stray Kids",
        idol: "Felix",
        album: "5-Star",
        version: "Limited Ver.",
        cardType: "Album photocard",
        rarity: "Uncommon",
        condition: "Near Mint",
        askingPrice: 24,
        imageUrl: "https://i.pinimg.com/236x/e2/c3/ef/e2c3ef34116390d34173a91ddca5f3e3.jpg",
        aliases: [
            "Felix 5-Star Limited",
            "SKZ Felix Five Star",
            "Lix 5-Star PC",
        ],
    },
    {
        group: "Stray Kids",
        idol: "Hyunjin",
        album: "Oddinary",
        version: "Soundwave Lucky Draw",
        cardType: "Lucky draw",
        rarity: "Rare",
        condition: "Mint",
        askingPrice: 62,
        imageUrl: "https://i.pinimg.com/236x/9e/13/69/9e1369e3a432c271f10eb91417aa2a8e.jpg",
        aliases: [
            "Hyunjin Oddinary LD",
            "SKZ Hyunjin Soundwave",
            "Jinnie Oddinary PC",
        ],
    },
    {
        group: "Stray Kids",
        idol: "Bang Chan",
        album: "Rock-Star",
        version: "Postcard Ver.",
        cardType: "Merch photocard",
        rarity: "Uncommon",
        condition: "Excellent",
        askingPrice: 18,
        imageUrl: "https://i.pinimg.com/236x/9e/13/69/9e1369e3a432c271f10eb91417aa2a8e.jpg",
        aliases: [
            "Bang Chan Rock-Star",
            "SKZ Chan Postcard",
            "Chan Merch PC",
        ],
    },
    {
        group: "Red Velvet",
        idol: "Irene",
        album: "Feel My Rhythm",
        version: "Orgel Ver.",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 18,
        imageUrl: "https://i.pinimg.com/736x/fc/06/02/fc0602b9506449e6b6047549f662ca0b.jpg",
        aliases: [
            "Irene FMR Orgel",
            "RV Irene Feel My Rhythm",
            "Bae Orgel PC",
        ],
    },
    {
        group: "Red Velvet",
        idol: "Seulgi",
        album: "Chill Kill",
        version: "Photobook Ver.",
        cardType: "Album photocard",
        rarity: "Uncommon",
        condition: "Excellent",
        askingPrice: 15,
        imageUrl: "https://i.pinimg.com/736x/fc/06/02/fc0602b9506449e6b6047549f662ca0b.jpg",
        aliases: [
            "Seulgi Chill Kill",
            "RV Seulgi Photobook",
            "Bear Chill Kill PC",
        ],
    },
    {
        group: "Red Velvet",
        idol: "Joy",
        album: "Queendom",
        version: "Girls Ver.",
        cardType: "Fanmeeting photocard",
        rarity: "Limited",
        condition: "Near Mint",
        askingPrice: 44,
        imageUrl: "https://i.pinimg.com/736x/fc/06/02/fc0602b9506449e6b6047549f662ca0b.jpg",
        aliases: [
            "Joy Queendom Fanmeeting",
            "RV Joy Girls Ver",
            "Sooyoung Queendom PC",
        ],
    },
    {
        group: "aespa",
        idol: "Karina",
        album: "Drama",
        version: "Giant Ver.",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Near Mint",
        askingPrice: 24,
        imageUrl: "https://i.pinimg.com/736x/fc/06/02/fc0602b9506449e6b6047549f662ca0b.jpg",
        aliases: [
            "Karina Drama Giant",
            "AES Karina Drama",
            "Rina Drama PC",
        ],
    },
    {
        group: "aespa",
        idol: "Winter",
        album: "My World",
        version: "Tabloid Ver.",
        cardType: "Album photocard",
        rarity: "Standard",
        condition: "Mint",
        askingPrice: 22,
        imageUrl: "https://i.pinimg.com/236x/7f/6f/97/7f6f97a5d37b72a027c48b813e388e74.jpg",
        aliases: [
            "Winter My World",
            "AES Winter Tabloid",
            "Minjeong My World PC",
        ],
    },
    {
        group: "aespa",
        idol: "Ningning",
        album: "Armageddon",
        version: "Superbeing Ver.",
        cardType: "POB",
        rarity: "Rare",
        condition: "Near Mint",
        askingPrice: 38,
        imageUrl: "https://i.pinimg.com/236x/96/d2/78/96d27896c21bbf3ff2a1a88939ed5680.jpg",
        aliases: [
            "Ningning Armageddon POB",
            "AES Ning Superbeing",
            "Ning Armageddon PC",
        ],
    },
];

async function seedCards() {
    try {
        await mongoose.connect(process.env.MONGO_URI);

        await Listing.deleteMany({});
        await Card.deleteMany({});

        const insertedCards = await Card.insertMany(cards);
        const demoListings = insertedCards.slice(0, 8).map((card, index) => ({
            cardId: card._id,
            sellerName: "Benny",
            price: [18.99, 22, 28.5, 34, 24, 19.5, 42, 36][index],
            condition: "Near Mint",
            userImageUrl: "",
            description: `Official ${card.idol} ${card.album} photocard, sleeved since pulled.`,
            status: "active",
        }));

        await Listing.insertMany(demoListings);

        console.log(`Seeded ${insertedCards.length} cards and ${demoListings.length} listings successfully`);
        process.exit(0);
    } catch (error) {
        console.error("Failed to seed cards:", error.message);
        process.exit(1);
    }
}

seedCards();
